version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: google-cloud-storage
    versions:
    - 1.37.1
  - dependency-name: google-cloud-bigquery
    versions:
    - 2.13.1
